### ISSUE TITLE
Weird "f" letters randomly added in code

### ISSUE THREAD

**Issue by catubc** [ctgk/PRML#12]
Hi. 
Thanks so much for writing this code, very useful for learning and teaching.

One weird issue is there are these places where the letter 'f' was prefixed to some strings.  Python2 crashes so I deleted them all.

Do you know what those are?

Thanks.

Here's an example from this file: /PRML/prml/rv/multivariate_gaussian_mixture.py

 `raise ValueError(f"sum of coef must be equal to 1 {coef}")
`

**Comment by tommyod** [comment]
They are [Python 3 f-Strings](https://realpython.com/python-f-strings/).

**Comment by catubc** [comment]
Thanks.  I couldn't get python3 to work with your code, so I had dropped into python2... but otherwise code works great.
