### ISSUE TITLE
draw() in Bernoulli distribution

### ISSUE THREAD

**Issue by gdxie1** [ctgk/PRML#35]
the line in the draw should change from  self.mu.n_ones / (self.mu.n_ones + self.mu.n_zeros) to

 **_(self.mu.n_ones - 1) / (self.mu.n_ones + self.mu.n_zeros -2)_**

**Comment by ctgk** [comment]
Should it be?

**Comment by gdxie1** [comment]
when you added the prior distribution, you should -1 and -2. Maybe I am wrong. Thank you anyway, it's a good project.

**Comment by ctgk** [comment]
Could you specify from which equation in PRML you though it should have -1 and -2?

**Comment by gdxie1** [comment]
Hi, I checked the book and found that you are right. I mistake the MAP of mu as the p(x=1|D) under Bayes. Sorry for this.

**Comment by ctgk** [comment]
Oh, I see! Yeah, it is confusing that we need them for estimation of mu and not for p(x=1||D).
